version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=eduardo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coopers
    volumes:
      - coopers_pg_data:/bitnami/postgresql

volumes:
  coopers_pg_data:
